######################################################################
# Automatically generated by qmake (3.0) ?? ???? 23 15:31:11 2015
######################################################################

TEMPLATE = app
TARGET = run
INCLUDEPATH += .
CONFIG += c++11
CONFIG-=app_bundle

# Input
SOURCES += main.cpp ../manager/manager.cpp
