######################################################################
# Automatically generated by qmake (3.0) ?? ???? 9 17:16:08 2015
######################################################################

TEMPLATE = app
TARGET = influence-ui
INCLUDEPATH += . ../manager/
QT += widgets
CONFIG += c++11
CONFIG-=app_bundle
# Input
HEADERS += ../manager/manager.hpp ui.hpp
SOURCES += ../manager/manager.cpp ui.cpp
